SELECT * FROM MOVIES
UPDATE MOVIES SET MONTHS = '01-JANUARY' WHERE DATEPART(MONTH,RELEASE_DATE)=1
UPDATE MOVIES SET MONTHS = '02-FEBRUARY' WHERE DATEPART(MONTH,RELEASE_DATE)=2
UPDATE MOVIES SET MONTHS = '03-MARCH' WHERE DATEPART(MONTH,RELEASE_DATE)=3
UPDATE MOVIES SET MONTHS = '04-APRIL' WHERE DATEPART(MONTH,RELEASE_DATE)=4
UPDATE MOVIES SET MONTHS = '05-MAY' WHERE DATEPART(MONTH,RELEASE_DATE)=5
UPDATE MOVIES SET MONTHS = '06-JUNE' WHERE DATEPART(MONTH,RELEASE_DATE)=6
UPDATE MOVIES SET MONTHS = '07-JULY' WHERE DATEPART(MONTH,RELEASE_DATE)=7
UPDATE MOVIES SET MONTHS = '08-AUGUST' WHERE DATEPART(MONTH,RELEASE_DATE)=8
UPDATE MOVIES SET MONTHS = '09-SEPTEMBER' WHERE DATEPART(MONTH,RELEASE_DATE)=9
UPDATE MOVIES SET MONTHS = '10-OCTOBER' WHERE DATEPART(MONTH,RELEASE_DATE)=10
UPDATE MOVIES SET MONTHS = '11-NOVEMBER' WHERE DATEPART(MONTH,RELEASE_DATE)=11
UPDATE MOVIES SET MONTHS = '12-DECEMBER' WHERE DATEPART(MONTH,RELEASE_DATE)=12

UPDATE MOVIES SET RELEASE_YEAR= DATEPART(YEAR,RELEASE_DATE)

SELECT RELEASE_YEAR, MONTHS, SUM(VOTE_COUNT) AS MONTHLY_VOTES FROM MOVIES
GROUP BY RELEASE_YEAR, MONTHS 
ORDER BY RELEASE_YEAR, MONTHLY_VOTES DESC

SELECT RELEASE_YEAR, COUNT (*) AS ROWCOUNT_ 
FROM MOVIES
GROUP BY RELEASE_YEAR 
ORDER BY RELEASE_YEAR 