INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY, DISTRICT, BIRTHDATE, GENDER) 
VALUES ('ZAHÝDENUR GÖKAY','KASTAMONU','GAZÝOSMANPAÞA','2002-10-11','K') 
SELECT *FROM CUSTOMERS
DELETE CUSTOMERS WHERE NATION IS NULL
SELECT* FROM CUSTOMERS
